# Generated by Django 4.1.2 on 2022-11-07 14:54

from django.db import migrations, models
import django.db.models.deletion
import notifications.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[(notifications.models.EnumNotifcationStatus['PENDING'], 'PENDING'), (notifications.models.EnumNotifcationStatus['SENDING'], 'SENDING'), (notifications.models.EnumNotifcationStatus['SUCCESS'], 'SUCCESS'), (notifications.models.EnumNotifcationStatus['PARTIAL_SUCCESS'], 'PARTIAL_SUCCESS'), (notifications.models.EnumNotifcationStatus['FAILURE'], 'FAILURE')], max_length=20)),
                ('type', models.CharField(choices=[(notifications.models.EnumNotificationType['EMAIL'], 'EMAIL'), (notifications.models.EnumNotificationType['SMS'], 'SMS'), (notifications.models.EnumNotificationType['API'], 'API')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(notifications.models.EnumNotifcationStatus['PENDING'], 'PENDING'), (notifications.models.EnumNotifcationStatus['SENDING'], 'SENDING'), (notifications.models.EnumNotifcationStatus['SUCCESS'], 'SUCCESS'), (notifications.models.EnumNotifcationStatus['PARTIAL_SUCCESS'], 'PARTIAL_SUCCESS'), (notifications.models.EnumNotifcationStatus['FAILURE'], 'FAILURE')], max_length=20)),
                ('notifcation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(notifications.models.EnumNotifcationStatus['PENDING'], 'PENDING'), (notifications.models.EnumNotifcationStatus['SENDING'], 'SENDING'), (notifications.models.EnumNotifcationStatus['SUCCESS'], 'SUCCESS'), (notifications.models.EnumNotifcationStatus['PARTIAL_SUCCESS'], 'PARTIAL_SUCCESS'), (notifications.models.EnumNotifcationStatus['FAILURE'], 'FAILURE')], max_length=20)),
                ('request', models.JSONField()),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
            ],
        ),
    ]
