# Generated by Django 4.1.2 on 2022-11-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nmessages', '0001_initial'),
        ('notifications', '0003_notification_created_at_notification_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='nmessage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nmessages.nmessage'),
        ),
    ]
