# Generated by Django 4.1.3 on 2022-11-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('ORGANIZATION', 'Organization'), ('INDIVIDUAL', 'Individual')], max_length=20),
        ),
    ]
